services:
  computeservice:
    build:
      dockerfile: Dockerfile
      context: ./computeapp
  dataservice:
    build:
      dockerfile: DataService/Dockerfile
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - computeservice